language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install doxygen

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  
branches:
    only:
        - master

packages:
- doxygen

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - doxygen Doxyfile

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u$USER_NAME:$BINTRAY_API_KEY "https://api.bintray.com/content/sosninroman/$BINTRAY_REPO_NAME/$BINTRAY_PACK_NAME/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $GITHUB_TOKEN
    on:
        branch: master
